/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    pages: Page;
    categories: Category;
    'market-areas': MarketArea;
    testimonials: Testimonial;
    'team-members': TeamMember;
    leads: Lead;
    'lead-activities': LeadActivity;
    'lead-tasks': LeadTask;
    'properties-interest': PropertiesInterest;
    'lead-conversations': LeadConversation;
    'automation-rules': AutomationRule;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'market-areas': MarketAreasSelect<false> | MarketAreasSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'lead-activities': LeadActivitiesSelect<false> | LeadActivitiesSelect<true>;
    'lead-tasks': LeadTasksSelect<false> | LeadTasksSelect<true>;
    'properties-interest': PropertiesInterestSelect<false> | PropertiesInterestSelect<true>;
    'lead-conversations': LeadConversationsSelect<false> | LeadConversationsSelect<true>;
    'automation-rules': AutomationRulesSelect<false> | AutomationRulesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'viewer' | 'api';
  firstName?: string | null;
  lastName?: string | null;
  /**
   * If checked, this user can be assigned leads via round-robin
   */
  isAssignable?: boolean | null;
  /**
   * Used for routing Spanish-speaking leads
   */
  speaksSpanish?: boolean | null;
  /**
   * Maximum number of open leads this user can be assigned
   */
  maxLeads?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Photographer or source credit
   */
  attribution?: string | null;
  /**
   * License type (e.g. Unsplash, CC-BY-SA, Public Domain)
   */
  license?: string | null;
  /**
   * Original URL where the image was sourced from
   */
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  author?: string | null;
  featuredImage?: (number | null) | Media;
  categories?: (number | Category)[] | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  sections?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            backgroundImage?: (number | null) | Media;
            ctaText?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            heading: string;
            description?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-areas".
 */
export interface MarketArea {
  id: number;
  city: string;
  slug: string;
  state?: string | null;
  /**
   * Short tagline shown under the city name
   */
  tagline?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * External image URL (used if no heroImage uploaded)
   */
  heroImageUrl?: string | null;
  imageAlt?: string | null;
  population?: number | null;
  /**
   * Monthly median rent ($)
   */
  medianRent?: number | null;
  /**
   * Body paragraphs for the market area detail page
   */
  description?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Bullet point highlights
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  author: string;
  text: string;
  rating: number;
  source?: ('google' | 'manual') | null;
  /**
   * Unique ID to prevent duplicate imports
   */
  googleReviewId?: string | null;
  publishedAt?: string | null;
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  title: string;
  bio?: string | null;
  email?: string | null;
  phone?: string | null;
  photo?: (number | null) | Media;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  status?:
    | (
        | 'new'
        | 'attempted_contact'
        | 'engaged'
        | 'tour_scheduled'
        | 'toured'
        | 'applied'
        | 'approved'
        | 'leased'
        | 'lost'
        | 'archived'
      )
    | null;
  assignedTo?: (number | null) | User;
  nextFollowUpAt?: string | null;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  preferredLanguage?: ('en' | 'es') | null;
  doNotContact?: boolean | null;
  smsOptIn?: boolean | null;
  emailOptIn?: boolean | null;
  source?:
    | ('zillow' | 'apartments_com' | 'website' | 'facebook' | 'instagram' | 'phone' | 'walk_in' | 'referral' | 'other')
    | null;
  sourceDetail?: string | null;
  leadType?: ('tenant' | 'owner' | 'vendor' | 'other') | null;
  stageReason?: string | null;
  notesSummary?: string | null;
  /**
   * Initial inquiry message (from contact form)
   */
  message?: string | null;
  desiredMoveInDate?: string | null;
  monthlyBudgetMin?: number | null;
  monthlyBudgetMax?: number | null;
  lastContactedAt?: string | null;
  lastInboundAt?: string | null;
  lastOutboundAt?: string | null;
  /**
   * AppFolio guest card ID for sync
   */
  appfolioGuestCardId?: string | null;
  /**
   * Rentzap application ID
   */
  rentzapApplicationId?: string | null;
  /**
   * ID of the original lead if this is a duplicate
   */
  isDuplicateOfLeadId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-activities".
 */
export interface LeadActivity {
  id: number;
  lead: number | Lead;
  type:
    | 'note'
    | 'email_sent'
    | 'email_received'
    | 'sms_sent'
    | 'sms_received'
    | 'call_logged'
    | 'voicemail'
    | 'task_created'
    | 'task_completed'
    | 'status_changed'
    | 'property_matched'
    | 'guest_card_created';
  direction?: ('inbound' | 'outbound' | 'internal') | null;
  body: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  performedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-tasks".
 */
export interface LeadTask {
  id: number;
  lead: number | Lead;
  title: string;
  description?: string | null;
  taskType:
    | 'follow_up_call'
    | 'follow_up_sms'
    | 'follow_up_email'
    | 'manual_review'
    | 'spanish_follow_up'
    | 'appfolio_push'
    | 'other';
  status?: ('open' | 'in_progress' | 'complete' | 'canceled' | 'overdue') | null;
  dueAt: string;
  completedAt?: string | null;
  assignedTo: number | User;
  priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties-interest".
 */
export interface PropertiesInterest {
  id: number;
  lead: number | Lead;
  /**
   * AppFolio listing ID
   */
  propertyExternalId?: string | null;
  propertyName?: string | null;
  unitIdentifier?: string | null;
  address?: string | null;
  rent?: number | null;
  availabilityDate?: string | null;
  /**
   * Link to the listing
   */
  sourceUrl?: string | null;
  status?: ('interested' | 'touring' | 'applied' | 'leased' | 'lost') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-conversations".
 */
export interface LeadConversation {
  id: number;
  lead: number | Lead;
  channel: 'email' | 'sms' | 'phone' | 'web' | 'social' | 'internal';
  subject?: string | null;
  body: string;
  direction?: ('inbound' | 'outbound') | null;
  language?: ('en' | 'es') | null;
  /**
   * Null for inbound messages from the lead
   */
  sentBy?: (number | null) | User;
  latestMessageAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-rules".
 */
export interface AutomationRule {
  id: number;
  name: string;
  description?: string | null;
  isActive?: boolean | null;
  triggerType: 'lead_created' | 'status_changed' | 'no_activity_timeout' | 'task_overdue' | 'follow_up_due';
  /**
   * JSON object with condition key-value pairs to match against the lead
   */
  conditions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  actionType: 'create_task' | 'change_status' | 'send_notification' | 'assign_lead';
  /**
   * JSON object with action parameters (varies by action type)
   */
  actionConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Execution order (lower = first)
   */
  priority?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'market-areas';
        value: number | MarketArea;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'lead-activities';
        value: number | LeadActivity;
      } | null)
    | ({
        relationTo: 'lead-tasks';
        value: number | LeadTask;
      } | null)
    | ({
        relationTo: 'properties-interest';
        value: number | PropertiesInterest;
      } | null)
    | ({
        relationTo: 'lead-conversations';
        value: number | LeadConversation;
      } | null)
    | ({
        relationTo: 'automation-rules';
        value: number | AutomationRule;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  isAssignable?: T;
  speaksSpanish?: T;
  maxLeads?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  attribution?: T;
  license?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  author?: T;
  featuredImage?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              ctaText?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-areas_select".
 */
export interface MarketAreasSelect<T extends boolean = true> {
  city?: T;
  slug?: T;
  state?: T;
  tagline?: T;
  heroImage?: T;
  heroImageUrl?: T;
  imageAlt?: T;
  population?: T;
  medianRent?: T;
  description?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  text?: T;
  rating?: T;
  source?: T;
  googleReviewId?: T;
  publishedAt?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  bio?: T;
  email?: T;
  phone?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  status?: T;
  assignedTo?: T;
  nextFollowUpAt?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  preferredLanguage?: T;
  doNotContact?: T;
  smsOptIn?: T;
  emailOptIn?: T;
  source?: T;
  sourceDetail?: T;
  leadType?: T;
  stageReason?: T;
  notesSummary?: T;
  message?: T;
  desiredMoveInDate?: T;
  monthlyBudgetMin?: T;
  monthlyBudgetMax?: T;
  lastContactedAt?: T;
  lastInboundAt?: T;
  lastOutboundAt?: T;
  appfolioGuestCardId?: T;
  rentzapApplicationId?: T;
  isDuplicateOfLeadId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-activities_select".
 */
export interface LeadActivitiesSelect<T extends boolean = true> {
  lead?: T;
  type?: T;
  direction?: T;
  body?: T;
  metadata?: T;
  performedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-tasks_select".
 */
export interface LeadTasksSelect<T extends boolean = true> {
  lead?: T;
  title?: T;
  description?: T;
  taskType?: T;
  status?: T;
  dueAt?: T;
  completedAt?: T;
  assignedTo?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties-interest_select".
 */
export interface PropertiesInterestSelect<T extends boolean = true> {
  lead?: T;
  propertyExternalId?: T;
  propertyName?: T;
  unitIdentifier?: T;
  address?: T;
  rent?: T;
  availabilityDate?: T;
  sourceUrl?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-conversations_select".
 */
export interface LeadConversationsSelect<T extends boolean = true> {
  lead?: T;
  channel?: T;
  subject?: T;
  body?: T;
  direction?: T;
  language?: T;
  sentBy?: T;
  latestMessageAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-rules_select".
 */
export interface AutomationRulesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  isActive?: T;
  triggerType?: T;
  conditions?: T;
  actionType?: T;
  actionConfig?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}